### PR TITLE
remove input

### PR DESCRIPTION
**Pull request by willkg**
vectorvictor is too annoying to keep around.

### CODE REVIEW

**Comment by pmclanahan** [comment]
sorry about that.

**Comment by pmclanahan** [comment]
@willkg what about it was too annoying? did someone say "surely" a lot?

**Comment by pmclanahan** [comment]
I've been meaning to remove that, but it comes up rarely in channels I'm in so I keep forgetting.

**Comment by willkg** [comment]
Yeah, the "surely" thing was kind of irritating. Plus #input is half bots. Plus when I tried to kick vectorvictor off, it hopped back on immediately. There isn't any way to invite/uninvite it. It's lacking some helpful commands.

**Comment by pmclanahan** [comment]
Yeah. I actually didn’t realize it would rejoin… it’s a pretty simple bot
and has no state storage at all, so it doesn’t do the invite/kick thing.
Thanks for the feedback.

**Pull request merged**
